INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (1,1,1,'eleifend luctus ultricies eu', 'id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat', 'http://dummyimage.com/158x100.png/cc0000/ffffff',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (2,1,5,'et magnis dis', 'mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 'http://dummyimage.com/186x100.png/dddddd/000000',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (3,3,4,'nulla facilisi cras non', 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', 'http://dummyimage.com/132x100.png/dddddd/000000',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (4,5,2,'id lobortis convallis', 'amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui', 'http://dummyimage.com/247x100.png/dddddd/000000',0);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (5,4,1,'in sapien iaculis', 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff',0);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (6,3,3,'tincidunt nulla', 'purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', 'http://dummyimage.com/247x100.png/dddddd/000000',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (7,2,3,'semper interdum mauris ullamcorper purus', 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque', 'http://dummyimage.com/237x100.png/ff4444/ffffff',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (8,2,4,'lorem', 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 'http://dummyimage.com/139x100.png/5fa2dd/ffffff',1);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (9,3,5,'turpis nec', 'quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', 'http://dummyimage.com/115x100.png/cc0000/ffffff',0);
INSERT INTO post (id,authorId,categoryId,title,content,thumbnail,published) VALUES (10,1,5,'ante ipsum primis in faucibus', 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis', 'http://dummyimage.com/126x100.png/cc0000/ffffff',1);

INSERT INTO post_tag (postId, tagId) VALUES (1,1);
INSERT INTO post_tag (postId, tagId) VALUES (1,2);
INSERT INTO post_tag (postId, tagId) VALUES (1,3);
INSERT INTO post_tag (postId, tagId) VALUES (2,3);
INSERT INTO post_tag (postId, tagId) VALUES (9,2);
INSERT INTO post_tag (postId, tagId) VALUES (7,2);
INSERT INTO post_tag (postId, tagId) VALUES (6,4);
INSERT INTO post_tag (postId, tagId) VALUES (10,5);
INSERT INTO post_tag (postId, tagId) VALUES (5,6);
INSERT INTO post_tag (postId, tagId) VALUES (4,8);